# Generated by Django 4.0.6 on 2022-09-23 19:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('other_names', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('position', models.CharField(max_length=100)),
                ('kit_number', models.IntegerField(unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('goals', models.IntegerField(default=0)),
                ('assist', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('meteors_logo', models.ImageField(blank=True, upload_to='')),
                ('oponent_logo', models.ImageField(blank=True, upload_to='')),
                ('goal_scorers', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('venue', models.CharField(max_length=200)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('kit', models.CharField(max_length=100)),
                ('goal_scorers', models.ManyToManyField(blank=True, null=True, related_name='playerset', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
