# Generated by Django 4.0.6 on 2022-10-06 07:46

from django.db import migrations, models
import players.models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_officials_delete_results_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=players.models.Player.upload_location),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(upload_to=players.models.Team.upload_location),
        ),
    ]
